import { api } from "../../convex/_generated/api";
import { getConvexClient } from "../../lib/convex/client";
import { NewsArticle, NewsSource, NewsCategory, NewsFilter } from '../types/news';
import logger from '../utils/logger';

const convex = getConvexClient();

export const NEWS_DEGRADATION_MESSAGE = 'No hay noticias disponibles en este momento. Configure fuentes de noticias en el panel de administración.';

export interface MarketNews {
  _id: string;
  _creationTime: number;
  title: string;
  summary: string;
  content: string;
  source: string;
  sourceUrl: string;
  sourceLogo?: string;
  category: 'forex' | 'crypto' | 'commodities' | 'indices' | 'stocks' | 'general';
  sentiment: 'bullish' | 'bearish' | 'neutral';
  relatedPairs: string[];
  relatedAssets: string[];
  imageUrl?: string;
  author?: {
    id: string;
    name: string;
    avatar: string;
    isVerified: boolean;
  };
  isAIGenerated: boolean;
  publishedAt: number;
  views: number;
  likes: string[];
  tags: string[];
  createdAt: number;
}

const SOURCE_CONFIG: Record<NewsSource, { name: string; icon: string; color: string; rssUrl?: string }> = {
  investing: { name: 'Investing.com', icon: '📈', color: '#1348c1' },
  myfxbook: { name: 'MyFXBook', icon: '📊', color: '#2ecc71' },
  forexfactory: { name: 'Forex Factory', icon: '🏭', color: '#e67e22' },
  bloomberg: { name: 'Bloomberg', icon: '💼', color: '#1a1a1a' },
  reuters: { name: 'Reuters', icon: '📰', color: '#cc0000' },
  cointelegraph: { name: 'CoinTelegraph', icon: '₿', color: '#4683c4' },
  coinmarketcap: { name: 'CoinMarketCap', icon: '📊', color: '#0055d5' },
  tradingview: { name: 'TradingView', icon: '📉', color: '#2196F3' },
  fxstreet: { name: 'FXStreet', icon: '💱', color: '#0073ba' },
  dailyfx: { name: 'DailyFX', icon: '📊', color: '#f7931a' },
};

function mapCategoryToInternal(category: string): 'forex' | 'crypto' | 'commodities' | 'indices' | 'stocks' | 'general' {
  const mapping: Record<string, 'forex' | 'crypto' | 'commodities' | 'indices' | 'stocks' | 'general'> = {
    'forex': 'forex',
    'crypto': 'crypto',
    'commodities': 'commodities',
    'indices': 'indices',
    'stocks': 'stocks',
    'general': 'general',
  };
  return mapping[category.toLowerCase()] || 'general';
}

function mapSentimentToInternal(sentiment: string): 'bullish' | 'bearish' | 'neutral' {
  const mapping: Record<string, 'bullish' | 'bearish' | 'neutral'> = {
    'bullish': 'bullish',
    'bearish': 'bearish',
    'neutral': 'neutral',
    'alcista': 'bullish',
    'bajista': 'bearish',
  };
  return mapping[sentiment.toLowerCase()] || 'neutral';
}

function marketNewsToNewsArticle(marketNews: MarketNews): NewsArticle {
  return {
    id: marketNews._id,
    title: marketNews.title,
    summary: marketNews.summary,
    content: marketNews.content,
    source: marketNews.source as NewsSource,
    author: marketNews.author?.name || marketNews.source,
    publishedAt: new Date(marketNews.publishedAt),
    url: marketNews.sourceUrl,
    imageUrl: marketNews.imageUrl || `https://picsum.photos/seed/${marketNews._id}/800/400`,
    category: mapCategoryToInternal(marketNews.category) as NewsCategory,
    tags: marketNews.tags,
    sentiment: mapSentimentToInternal(marketNews.sentiment) as 'bullish' | 'bearish' | 'neutral',
    relatedPairs: marketNews.relatedPairs,
    views: marketNews.views,
    likes: marketNews.likes,
  };
}
class NewsService {
  private cachedNews: NewsArticle[] = [];
  private lastFetch: Date | null = null;
  private isFetching: boolean = false;
  private convexEnabled: boolean = false;
  private isDegraded: boolean = false;

  enableConvex(convexNews: MarketNews[]) {
    this.convexEnabled = true;
    this.cachedNews = convexNews.map(marketNewsToNewsArticle);
    this.lastFetch = new Date();
    this.isDegraded = this.cachedNews.length === 0;
  }

  private mapConvexNewsToArticle(convexNews: any): NewsArticle {
    return {
      id: convexNews._id || convexNews.id,
      title: convexNews.title || '',
      summary: convexNews.summary || '',
      content: convexNews.content || '',
      source: (convexNews.source?.toLowerCase() as NewsSource) || 'investing',
      author: convexNews.author?.name || convexNews.source,
      publishedAt: new Date(convexNews.publishedAt || Date.now()),
      url: convexNews.sourceUrl || '',
      imageUrl: convexNews.imageUrl || undefined,
      category: (convexNews.category as NewsCategory) || 'general',
      tags: convexNews.tags || [],
      sentiment: convexNews.sentiment || 'neutral',
      relatedPairs: convexNews.relatedPairs || [],
      views: convexNews.views || 0,
      isAutoGenerated: convexNews.isAIGenerated || false,
    };
  }

  async fetchNews(filter?: NewsFilter): Promise<NewsArticle[]> {
    if (this.isFetching) {
      return this.getCachedNews(filter);
    }

    if (!this.convexEnabled || this.cachedNews.length === 0) {
      this.isFetching = true;
      try {
        if (convex) {
          const convexNews = await convex.query(api.market.marketNews.getRecentNews, { hours: 24 });
          this.cachedNews = (convexNews || []).map(n => this.mapConvexNewsToArticle(n));
          this.convexEnabled = true;
          this.lastFetch = new Date();
          this.isDegraded = this.cachedNews.length === 0;
        } else {
          logger.warn('[NewsService] Convex not available');
          this.cachedNews = [];
          this.isDegraded = true;
        }
      } catch (error) {
        logger.error('[NewsService] Error fetching from Convex:', error);
        this.cachedNews = [];
        this.isDegraded = true;
      } finally {
        this.isFetching = false;
      }
    }

    return this.getCachedNews(filter);
  }

  isInDegradedMode(): boolean {
    return this.isDegraded;
  }

  getDegradationMessage(): string {
    return NEWS_DEGRADATION_MESSAGE;
  }

  private getCachedNews(filter?: NewsFilter): NewsArticle[] {
    let filtered = [...this.cachedNews];

    if (filter) {
      if (filter.sources?.length) {
        filtered = filtered.filter(n => filter.sources!.includes(n.source));
      }
      if (filter.categories?.length) {
        filtered = filtered.filter(n => filter.categories!.includes(n.category));
      }
      if (filter.dateFrom) {
        filtered = filtered.filter(n => n.publishedAt >= filter.dateFrom!);
      }
      if (filter.dateTo) {
        filtered = filtered.filter(n => n.publishedAt <= filter.dateTo!);
      }
      if (filter.searchQuery) {
        const query = filter.searchQuery.toLowerCase();
        filtered = filtered.filter(n =>
          n.title.toLowerCase().includes(query) ||
          n.summary.toLowerCase().includes(query) ||
          n.tags.some(t => t.toLowerCase().includes(query))
        );
      }
      if (filter.sentiment) {
        const sentimentMap: Record<string, string> = {
          'bullish': 'bullish',
          'alcista': 'bullish',
          'bearish': 'bearish',
          'bajista': 'bearish',
          'neutral': 'neutral',
        };
        const mappedSentiment = sentimentMap[filter.sentiment.toLowerCase()];
        if (mappedSentiment) {
          filtered = filtered.filter(n => n.sentiment === mappedSentiment);
        }
      }
    }

    return filtered.sort((a, b) => b.publishedAt.getTime() - a.publishedAt.getTime());
  }

  async getNewsById(id: string): Promise<NewsArticle | null> {
    return this.cachedNews.find(n => n.id === id) || null;
  }

  async getTrendingNews(limit: number = 5): Promise<NewsArticle[]> {
    if (this.cachedNews.length === 0) {
      await this.fetchNews();
    }
    return [...this.cachedNews]
      .sort((a, b) => (b.views || 0) - (a.views || 0))
      .slice(0, limit);
  }

  async getLatestNews(limit: number = 10): Promise<NewsArticle[]> {
    if (this.cachedNews.length === 0) {
      await this.fetchNews();
    }
    return [...this.cachedNews]
      .sort((a, b) => b.publishedAt.getTime() - a.publishedAt.getTime())
      .slice(0, limit);
  }

  async getNewsBySource(source: NewsSource, limit?: number): Promise<NewsArticle[]> {
    if (this.cachedNews.length === 0) {
      await this.fetchNews();
    }
    const news = this.cachedNews
      .filter(n => n.source === source)
      .sort((a, b) => b.publishedAt.getTime() - a.publishedAt.getTime());

    return limit ? news.slice(0, limit) : news;
  }

  async getNewsByCategory(category: NewsCategory, limit?: number): Promise<NewsArticle[]> {
    if (this.cachedNews.length === 0) {
      await this.fetchNews();
    }
    const news = this.cachedNews
      .filter(n => n.category === category)
      .sort((a, b) => b.publishedAt.getTime() - a.publishedAt.getTime());

    return limit ? news.slice(0, limit) : news;
  }

  async getRelatedNews(article: NewsArticle, limit: number = 5): Promise<NewsArticle[]> {
    if (this.cachedNews.length === 0) {
      await this.fetchNews();
    }
    const related = this.cachedNews.filter(n => 

      n.id !== article.id &&
      (n.category === article.category ||
        n.relatedPairs?.some(p => article.relatedPairs?.includes(p)) ||
        n.tags.some(t => article.tags.includes(t)))
    );

    return related.slice(0, limit);
  }

  getSourceInfo(source: NewsSource) {
    return SOURCE_CONFIG[source];
  }

  async refreshNews(convexNews?: MarketNews[]): Promise<void> {
    if (convexNews) {
      this.enableConvex(convexNews);
    } else {
      this.convexEnabled = false;
      this.cachedNews = [];
      this.lastFetch = null;
      this.isDegraded = false;
      await this.fetchNews();
    }
  }
}

export const newsService = new NewsService();
export { SOURCE_CONFIG };
