export interface NewsArticle {
  id: string;
  title: string;
  summary: string;
  content: string;
  source: NewsSource;
  author?: string;
  publishedAt: Date;
  url: string;
  imageUrl?: string;
  category: NewsCategory;
  tags: string[];
  sentiment?: 'bullish' | 'bearish' | 'neutral';
  relatedPairs?: string[];
  views?: number;
  likes?: string[];
  isAutoGenerated?: boolean;
  agentId?: string;
}

export type NewsSource = 
  | 'investing'
  | 'myfxbook'
  | 'forexfactory'
  | 'bloomberg'
  | 'reuters'
  | 'cointelegraph'
  | 'coinmarketcap'
  | 'tradingview'
  | 'fxstreet'
  | 'dailyfx';

export type NewsCategory = 
  | 'forex'
  | 'crypto'
  | 'indices'
  | 'commodities'
  | 'stocks'
  | 'economic'
  | 'analysis'
  | 'education'
  | 'general';

export interface NewsFilter {
  sources?: NewsSource[];
  categories?: NewsCategory[];
  dateFrom?: Date;
  dateTo?: Date;
  searchQuery?: string;
  sentiment?: 'bullish' | 'bearish' | 'neutral';
}

export interface NewsPreferences {
  enabled: boolean;
  autoPublish: boolean;
  sources: NewsSource[];
  categories: NewsCategory[];
  publishInterval: number;
  includeAnalysis: boolean;
}
