import { Icon as IconifyIcon } from '@iconify/react';

interface IconProps {
  name: string;
  className?: string;
  width?: string | number;
  height?: string | number;
  flip?: string;
  rotate?: number;
  color?: string;
}

export function Icon({ 
  name, 
  className = '', 
  width = 24, 
  height,
  flip,
  rotate,
  color 
}: IconProps) {
  return (
    <IconifyIcon
      icon={`ci:${name}`}
      className={className}
      width={width}
      height={height || width}
      flip={flip}
      rotate={rotate}
      color={color}
    />
  );
}

export const iconNames = {
  home: 'home',
  user: 'user',
  users: 'users',
  settings: 'settings',
  search: 'search',
  menu: 'menu',
  close: 'close',
  plus: 'plus',
  minus: 'minus',
  check: 'check',
  checkCircle: 'check-circle',
  x: 'x',
  arrowUp: 'arrow-up',
  arrowDown: 'arrow-down',
  arrowLeft: 'arrow-left',
  arrowRight: 'arrow-right',
  chevronUp: 'chevron-up',
  chevronDown: 'chevron-down',
  chevronLeft: 'chevron-left',
  chevronRight: 'chevron-right',
  star: 'star',
  starOutline: 'star-outline',
  heart: 'heart',
  heartOutline: 'heart-outline',
  bookmark: 'bookmark',
  bookmarkOutline: 'bookmark-outline',
  bell: 'bell',
  bellOutline: 'bell-outline',
  mail: 'mail',
  mailOutline: 'mail-outline',
  phone: 'phone',
  lock: 'lock',
  lockOpen: 'lock-open',
  eye: 'eye',
  eyeOutline: 'eye-outline',
  eyeClosed: 'eye-closed',
  trash: 'trash',
  trashOutline: 'trash-outline',
  pencil: 'pencil',
  edit: 'edit',
  copy: 'copy',
  share: 'share',
  download: 'download',
  upload: 'upload',
  image: 'image',
  camera: 'camera',
  video: 'video',
  play: 'play',
  pause: 'pause',
  stop: 'stop',
  skipForward: 'skip-forward',
  skipBack: 'skip-back',
  fastForward: 'fast-forward',
  rewind: 'rewind',
  shuffle: 'shuffle',
  repeat: 'repeat',
  volume: 'volume',
  volumeMute: 'volume-mute',
  mic: 'mic',
  micOutline: 'mic-outline',
  location: 'location',
  map: 'map',
  calendar: 'calendar',
  clock: 'clock',
  timer: 'timer',
  flag: 'flag',
  tag: 'tag',
  shoppingCart: 'shopping-cart',
  creditCard: 'credit-card',
  wallet: 'wallet',
  dollar: 'dollar',
  chart: 'chart',
  trendingUp: 'trending-up',
  trendingDown: 'trending-down',
  activity: 'activity',
  zap: 'zap',
  bolt: 'bolt',
  sun: 'sun',
  moon: 'moon',
  cloud: 'cloud',
  cloudOutline: 'cloud-outline',
  weather: 'weather',
  globe: 'globe',
  link: 'link',
  linkOutline: 'link-outline',
  unlink: 'unlink',
  anchor: 'anchor',
  paperclip: 'paperclip',
  filter: 'filter',
  sort: 'sort',
  list: 'list',
  grid: 'grid',
  layout: 'layout',
  columns: 'columns',
  rows: 'rows',
  dashboard: 'dashboard',
  tools: 'tools',
  wrench: 'wrench',
  screwdriver: 'screwdriver',
  cog: 'cog',
  slider: 'slider',
  refresh: 'refresh',
  sync: 'sync',
  rotate: 'rotate',
  logOut: 'log-out',
  login: 'login',
  addUser: 'add-user',
  removeUser: 'remove-user',
  userPlus: 'user-plus',
  userMinus: 'user-minus',
  group: 'group',
  groupOutline: 'group-outline',
  medal: 'medal',
  trophy: 'trophy',
  crown: 'crown',
  shield: 'shield',
  shieldOutline: 'shield-outline',
  flagOutline: 'flag-outline',
  target: 'target',
  crosshair: 'crosshair',
  bug: 'bug',
  code: 'code',
  codeOutline: 'code-outline',
  terminal: 'terminal',
  command: 'command',
  keyboard: 'keyboard',
  laptop: 'laptop',
  monitor: 'monitor',
  smartphone: 'smartphone',
  tablet: 'tablet',
  wifi: 'wifi',
  wifiOutline: 'wifi-outline',
  bluetooth: 'bluetooth',
  signal: 'signal',
  battery: 'battery',
  plug: 'plug',
  power: 'power',
  bookmarked: 'bookmarked',
  unbookmarked: 'unbookmarked',
  celebration: 'celebration',
  gift: 'gift',
  fire: 'fire',
  sparkle: 'sparkle',
  notification: 'notification',
  notificationOutline: 'notification-outline',
  info: 'info',
  infoOutline: 'info-outline',
  alertTriangle: 'alert-triangle',
  alertCircle: 'alert-circle',
  alertOctagon: 'alert-octagon',
  question: 'question',
  questionOutline: 'question-outline',
  help: 'help',
  helpOutline: 'help-outline',
  document: 'document',
  documentOutline: 'document-outline',
  folder: 'folder',
  folderOutline: 'folder-outline',
  folderOpen: 'folder-open',
  archive: 'archive',
  inbox: 'inbox',
  paperPlane: 'paper-plane',
  send: 'send',
  message: 'message',
  messageOutline: 'message-outline',
  chat: 'chat',
  chatOutline: 'chat-outline',
  comment: 'comment',
  commentOutline: 'comment-outline',
  compose: 'compose',
  feed: 'feed',
  news: 'news',
  newspaper: 'newspaper',
  bookmarkPlus: 'bookmark-plus',
  bookmarkMinus: 'bookmark-minus',
  export: 'export',
  import: 'import',
  externalLink: 'external-link',
  externalLinkOutline: 'external-link-outline',
  refreshOutline: 'refresh-outline',
  homeOutline: 'home-outline',
  userOutline: 'user-outline',
  usersOutline: 'users-outline',
  settingsOutline: 'settings-outline',
  searchOutline: 'search-outline',
  menuOutline: 'menu-outline',
  plusOutline: 'plus-outline',
  minusOutline: 'minus-outline',
} as const;

export type IconName = keyof typeof iconNames;
